{% set name = "nrtk" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nrtk-{{ version }}.tar.gz
  sha256: 6d941e95797be4a5a5856c7bd3c90b914d6ea7e12290efc8f1c7ea77b0e784b1

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [py==38]

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.23.1,<1.25  # [py<312]
    - numpy >=1.26  # [py>=312]
    - opencv >=4.6
    - pillow >=10.2.0
    - scikit-image >=0.21,<0.22  # [py<312]
    - scikit-image >=0.22  # [py>=312]
    - smqtk-classifier >=0.19.0
    - smqtk-core >=0.19
    - smqtk-detection >=0.19.0
    - smqtk-image-io >=0.17.1
    - tqdm >=4.64
    - pybsm >=0.2.0
    - pycocotools >=2.0.6
test:
  imports:
    - nrtk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/nrtk/
  summary: |
    The nrtk package is an open source toolkit for evaluating the natural robustness of
    computer vision algorithms to various perturbations, including sensor-specific
    changes to camera focal length, aperture diameter, etc
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bjrichardwebster
    - Purg
    - barry-ravichandran
