{% set name = "nrtk" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nrtk-{{ version }}.tar.gz
  sha256: 8239b76e341c2dd828944ac3fe0802389cea870e1633507d4f277221e70c7992

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core <2.0
  run:
    - python
    - numpy >=1.22,<2.0
    - pillow >=10.3.0
    - pybsm >=0.10.2
    - setuptools >=65.6.1
    - scikit-image >=0.20
    - smqtk-classifier >=0.19.0
    - smqtk-core >=0.19
    - smqtk-detection >=0.19.0
    - smqtk-image-io >=0.17.1
    - tqdm >=4.64
    - typing-extensions >=4.5.0
    - pycocotools >=2.0.6
    - maite ~=0.7.1
    - fastapi >=0.110.0
    - uvicorn >=0.29.0
    - pydantic >=2.6.4
    - pydantic-settings >=2.2.1
    - kwcoco >=0.2.18
    - scipy >=1.10.0
    - shapely >=2.0.7

test:
  imports:
    - nrtk
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: nrtk
  - name: nrtk-graphics
    requirements:
      host:
        - python
      run:
        - python
        - py-opencv >=4.6.0
        - {{ pin_subpackage('nrtk', exact=True) }}
    test:
      imports:
        - nrtk
        - cv2
      commands:
        - pip check
      requires:
        - pip
  - name: nrtk-headless
    requirements:
      host:
        - python
      run:
        - python
        - opencv >=4.6.0
        - {{ pin_subpackage('nrtk', exact=True) }}
    test:
      imports:
        - nrtk
        - cv2
      commands:
        - pip check
      requires:
        - pip
        - libopencv *=headless*  # [not win]

about:
  home: https://pypi.org/project/nrtk/
  summary: |
    The nrtk package is an open source toolkit for evaluating the natural robustness of
    computer vision algorithms to various perturbations, including sensor-specific
    changes to camera focal length, aperture diameter, etc
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martinduffy1
    - alexander-lynch
    - eveenhuis
    - bjrichardwebster
    - Purg
    - barry-ravichandran
